### ISSUE TITLE
The question when calculating focal_pixel

### ISSUE THREAD

**Issue by Xin-97** [szymanowiczs/splatter-image#13]
Hi @szymanowiczs,

Thanks for your great work. I am a new one in this field. I found a formula for focal_length to focal_pixel, F(mm) = F(pixels) * SensorWidth(mm) / ImageWidth (pixel).  When you calculate focal_pixel here https://github.com/szymanowiczs/splatter-image/blob/a2cbd6df67b2e34d10c8808dc1e8fe0daf4c02c7/scene/dataset_readers.py#L114 Why you set sensorwidth to 2? Thanks!

**Comment by StellarCheng** [comment]
Thanks for your work! And I also wonder how to find some parameters in the configs too.
<img width="410" alt="截屏2024-01-15 21 05 27" src="https://github.com/szymanowiczs/splatter-image/assets/122878624/aaa46039-fbe8-4da1-b7dc-abcbcac029ae">

**Comment by szymanowiczs** [comment]
Hi @Xin-97 this is because CO3D cameras are in NDC coordinates: see bottom of the page here. https://pytorch3d.org/docs/cameras.
