### ISSUE TITLE
Multi-GPU support

### ISSUE THREAD

**Issue by thucz** [szymanowiczs/splatter-image#14]
Does the code support multi-gpu running? When I used the code in a 2-gpu machine. It seems that it only used one GPU

**Comment by szymanowiczs** [comment]
Yes - currently this only supports a single GPU because training and testing is fast enough to do experimentation with one GPU. Multi-GPU support could indeed make it quicker, but I don't anticipate adding that functionality soon so feel free to make a PR if you would like to.
