### ISSUE TITLE
Link to CO3D dataset download refers to v1, but code is expecting the v2 format

### ISSUE THREAD

**Issue by killogreT** [szymanowiczs/splatter-image#19]
There's a repo for downloading CO3D v2 conveniently:
https://github.com/facebookresearch/co3d

**Comment by johnren-code** [comment]
Hi, I would like to know what is the main difference between CO3D dataset and ShapeNetSRN dataset?

**Comment by Torment123** [comment]
> Hi, I would like to know what is the main difference between CO3D dataset and ShapeNetSRN dataset?

shapenet is synthetic dataset, and CO3D contains real world images

**Comment by szymanowiczs** [comment]
Thanks @killogreT - I made an update to Readme
