### ISSUE TITLE
Errors when running single-view models

### ISSUE THREAD

**Issue by LaFeuilleMorte** [szymanowiczs/splatter-image#2]
Hi, thanks for your great work. I encountered an error when I was trying to run :
python train_network.py +dataset=[cars,chairs,hydrants,teddybears]
But I observed such an error in my terminal:

In 'default_config': Could not find 'hydra/defaults'

Available options in 'hydra':
        config
Config search path:
        provider=hydra, path=pkg://hydra.conf
        provider=main, path=file://E:\AiMagic\Gaussians\GenerativeGS\splatter-image\configs
        provider=hydra-colorlog, path=pkg://hydra_plugins.hydra_colorlog.conf
        provider=schema, path=structured://

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

After I checked the ./configs folder, there's no folder named "hydra", nor a file named "defaults" inside it. Is that why this error happened. (I know little about the hydra)
And my platform is Windows 10 professional, RTX 3090 GPU.

Best

**Comment by xiongyuyang** [comment]
same question

**Comment by LaFeuilleMorte** [comment]
> same question

看上去像是缺少一个文件，没有hydra/defaults这个文件

**Comment by szymanowiczs** [comment]
Closing the issue as solved now with the latest commit
