### ISSUE TITLE
Training with higher resolution images

### ISSUE THREAD

**Issue by johnren-code** [szymanowiczs/splatter-image#20]
Hi, I would like to ask if splatter image can be trained with higher resolution images? Like 256 or 512, if so, do I need to make changes to the network architecture?

**Comment by szymanowiczs** [comment]
No, you should be directly able to use the same architecture. Be careful about camera parameters though, in particular intrinsics (focal length, principal point) as they change with resizing - you should make sure the unprojection along camera rays and projection to image still works as expected.
