### ISSUE TITLE
How-To use the splatter-image on own images

### ISSUE THREAD

**Issue by DiamondGlassDrill** [szymanowiczs/splatter-image#21]
Just from the reading perspective an awesome work!
Congrats.

Yet I couldn't step into training on cars training dataset, but rather to do the cars only, I would love todo my own images.

Could u provide the steps in a short How-To to be taken that I can use any image to 3D?

Thanks in advance for the support.

**Comment by Ira569** [comment]
my advice, maybe you could refer to srn.py，and add your code  to make your dataset adopt the srn_car dataset format.
I think the main challenge is to find out the meaning of transform matrix and projection matrix in srn.py

**Comment by szymanowiczs** [comment]
Indeed - you need to modify the dataloader. Thanks @Ira569 for pointing this out - for more details about camera conventions see the Readme.
