### ISSUE TITLE
A bug in srn.py

### ISSUE THREAD

**Issue by River-Zhang** [szymanowiczs/splatter-image#25]
Hi, it an excellent work. But I came into something wrong.
I find that the code in srn.py line 22 is `  self.base_path = os.path.join(SHAPENET_DATASET_ROOT, "srn_{}/{}_{}".format(cfg.data.category,
                                                                              cfg.data.category,
                                                                              cfg.data.category,
                                                                              dataset_name))`

However this causes a wrong path, shouldn't it be
` self.base_path = os.path.join(SHAPENET_DATASET_ROOT, "srn_{}/{}_{}".format(cfg.data.category,
                                                                              cfg.data.category,
                                                                              dataset_name))`
The number of parameter is three not four.

**Comment by yuedajiong** [comment]
https://github.com/szymanowiczs/splatter-image/issues/10#issuecomment-1994176872

**Comment by szymanowiczs** [comment]
Fixed now.
