### ISSUE TITLE
Question about  ray_dirs.

### ISSUE THREAD

**Issue by karaokenoway** [szymanowiczs/splatter-image#27]
Hi, what a great job!!
I have a question about the process of initializing ray_dirs. 
why ray_dirs are divided by focal in this code?? If i use other data to train, should i take the same steps?
![Snipaste_2024-03-04_19-38-42](https://github.com/szymanowiczs/splatter-image/assets/65578982/c76e6cf6-9e46-414a-a546-8e7cff25745a)

**Comment by szymanowiczs** [comment]
hi @karaokenoway apologies for a late reply. ray_dirs should be [u/f, v/f, 1] where u, v are x, y locations of the pixel centres (in pixel units) and f is focal length in pixels. For cars and chairs this is done when it is initialised, as encoded above. If focal length varies across source images, the buffer is set to be [u, v, 1] and is divided by focal length in the reconstruction method. 

You definitely need to do this for your own data too.

**Comment by SravanChittupalli** [comment]
Hey! This would only work if we assume the intrinsic matrix is a diagonal matrix. Can you please explain why we are assuming that? 

Please correct me if I am wrong. Thank you!
