### ISSUE TITLE
Confusion regarding this stereoscopic reconstruction technique direction

### ISSUE THREAD

**Issue by yuedajiong** [szymanowiczs/splatter-image#32]
Using GS as the output, in my view, GS is essentially a 2.5D output. 

Due to the limitations in representing such as: potential big size of Gaussian points, and opacity that may not closely approximate the physical world, maybe very diffucut to extract surface representations like mesh.
Only when GS is subject to strong constraints similar to SuGaR. This is what truly defines 3D.

In short, how to control the algorihtm to generate a surface well-aligned GS, and no garbage points.

Individual highly appreciates the technical approach of this paper, which directly generates three-dimensional output representations based on fewer input constraints/just image. It should be 'perfect' if the generation process by imposing constraints: the Gaussian points closer to the surface, the flat orientation of Gaussian points facing the surface, avoiding excessive size of Gaussian points, and achieving good opacity for non-transparent physics, etc.

**Comment by johnren-code** [comment]
Same question, do you think that adding some additional supervision information to this work, such as depth supervision, would make the final result better and give a better shape?

**Comment by johnren-code** [comment]
I also think that the idea of this work is very innovative, and there are many things that can continue to be deeper and more innovative on this work.

**Comment by szymanowiczs** [comment]
Indeed, there are no constraints on where the points lie, the only signal is from novel view synthesis losses (L2 and LPIPS losses on novel views). Improving shape quality is an important direction for future work.
