### ISSUE TITLE
Can't import utils until added __init__.py

### ISSUE THREAD

**Issue by killer2-1** [szymanowiczs/splatter-image#33]
Thank you for your great work. I was trying to run  python train_network.py when it returns ModuleNotFoundError: No module named 'utils.graphics_utils', and the problem was solved after I added the path of parent folder to sys.path and created an empty __init__.py file to the 'scene' folder. Wonder if anyone has met the same problem?

**Comment by szymanowiczs** [comment]
Hi @killer2-1 thanks for pointing this out and glad you managed to resolve it.
