### ISSUE TITLE
co3d dataset training config 

### ISSUE THREAD

**Issue by jwubz123** [szymanowiczs/splatter-image#38]
Hi, 

Thanks a lot for such interesting work. I am now trying to train your model on CO3D dataset but cannot reproduce the reuslt in your paper. Will you release the config file and checkpoint for it?

Best

**Comment by szymanowiczs** [comment]
Yes, there's an update to the repo and paper coming next week - all will be released then.

**Comment by jwubz123** [comment]
Thanks a lot for your kind reply.
