### ISSUE TITLE
can not upload image in demo.

### ISSUE THREAD

**Issue by yuedajiong** [szymanowiczs/splatter-image#39]
as title

**Comment by szymanowiczs** [comment]
Can you tell me more?

**Comment by yuedajiong** [comment]
1.   go to your demo page: https://huggingface.co/spaces/szymanowiczs/splatter_image   (this page is very slow.)
2.   upload any png image (I tried different images)
3.   no any response.
 but, if I click the demo images that is OK.  

tried:
![Lion](https://github.com/szymanowiczs/splatter-image/assets/52232153/5be033a2-3943-4fd0-b26a-7a2e8efcd7e1)
![Wizard](https://github.com/szymanowiczs/splatter-image/assets/52232153/e0cb3d4c-5c1c-4886-a72c-319dcf19b123)

**Comment by szymanowiczs** [comment]
From what I gather it might be something to do with the Gradio version. I've rebuilt the space and it works fine again but I'll keep looking into it.

**Comment by yuedajiong** [comment]
Hi, great-master:
   It is OK now; and the quality is very good.
Thanks

**Comment by yuedajiong** [comment]
Dear @szymanowiczs:
    a question about pose, including camera pose and object pose.

    your code:
    "pos = torch.bmm(pos<HERE>, source_cameras_view_to_world)"

     source_cameras_view_to_world:  means the 200 preset camera poses?
     pos<HERE>:  the pose of object: while infer, the pose is predicted by network; while train, if dataset is 3D objects, the pose is known in loop rendering, right?   (if dataset is NOT 3D objects, we need colmap or others pose estimation step? right?)

Thanks

**Comment by szymanowiczs** [comment]
Yes, if the cameras are not known you need to set them to where you want to render the reconstruction from for visualisation. In this case we have objects, so a loop is a reasonable way to visualise them. For scenes you might want to choose another camera visualisation path, for example figures of 8, small circles, camera going around. Essentially depends on how you want to visualise the reconstruction.

But note that you don't need them to run the network or reconstruction, you only need them for visualisation.
