### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Key 'diffusion' is not in struct

### ISSUE THREAD

**Issue by StellarCheng** [szymanowiczs/splatter-image#4]
Thanks for your excellent work! When I run the code it raise the issues as following:
Setting up [LPIPS] perceptual loss: trunk [vgg], v[0.1], spatial [off] [01/01 16:02:40]
/home/chencheng/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/chencheng/.local/lib/python3.10/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=VGG16_Weights.IMAGENET1K_V1`. You can also use `weights=VGG16_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Loading model from: /home/chencheng/.local/lib/python3.10/site-packages/lpips/weights/v0.1/vgg.pth [01/01 16:02:41]
Error executing job with overrides: ['+dataset=[cars]']
Traceback (most recent call last):
  File "/home/chencheng/code/splatter-image/train_network.py", line 128, in main
    dataset = get_dataset(cfg, "train")
  File "/home/chencheng/code/splatter-image/scene/dataset_factory.py", line 6, in get_dataset
    return SRNDataset(cfg, name)
  File "/home/chencheng/code/splatter-image/scene/srn.py", line 49, in __init__
    if cfg.diffusion.channel_mult_noise == 0:
omegaconf.errors.ConfigAttributeError: Key 'diffusion' is not in struct
    full_key: diffusion
    object_type=dict

Set the environment variable HYDRA_FULL_ERROR=1 for a complete stack trace.

And i find all diffusion related configs is miss in the current repo, could you please help me to check these issue

**Comment by StellarCheng** [comment]
And I also encountered this issue:
   data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/chencheng/code/splatter-image/scene/srn.py", line 144, in __getitem__
    self.load_example_id(example_id, intrin_path)
  File "/home/chencheng/code/splatter-image/scene/srn.py", line 92, in load_example_id
    if self.cfg.data.rescale_to_cars:
omegaconf.errors.ConfigAttributeError: Key 'rescale_to_cars' is not in struct
    full_key: data.rescale_to_cars
    object_type=dict

It seems that the current config file miss some parameters.

**Comment by szymanowiczs** [comment]
Hi, indeed there was a mistake - I now removed the deprecated config options. Let me know if you encounter any further problems.
