### ISSUE TITLE
What about the gaussians that are switched off in the end?

### ISSUE THREAD

**Issue by Colezwhy** [szymanowiczs/splatter-image#41]
Dear author, thank you for your excellent job.
What is the proportion of the type of gaussians that are finally switched off(opacity=0)? And will it be a redundant thing to predict a gaussian for each pixel?

**Comment by szymanowiczs** [comment]
Yes, it's possible that some of them are redundant. There are quite a few that are fully switched off, maybe as many as half but that's just a rough estimate.
