### ISSUE TITLE
Missing lvis-annotations-filtered.json

### ISSUE THREAD

**Issue by Chrixtar** [szymanowiczs/splatter-image#42]
Hi Stan,

thank you very much for your great codebase!
In the readme, you state "please download lvis-annotations-filtered.json from the model repository", but I cannot find it.

Could you please point me to the location or upload the file in case you forgot it?

Best
Chris

**Comment by yuedajiong** [comment]
OMG!
here:
https://huggingface.co/szymanowiczs/splatter-image-v1/blob/main/lvis-annotations-filtered.json

**Comment by Chrixtar** [comment]
Yes, thank you. As mentioned above, I found it, but just kept the issue open as a reminder of the wrong link in the Readme...

**Comment by szymanowiczs** [comment]
Many thanks for pointing this out @Chrixtar ! Updated the readme.
