### ISSUE TITLE
TypeError: cannot create 'cython_function_or_method' instances

### ISSUE THREAD

**Issue by dlwns97** [szymanowiczs/splatter-image#43]
Hi, I am so glad to see your great works on splatter-image.

I want to reproduce your works and training the model on [cars, chairs] is my first step.
But I got some errors on it.

Firstly, I got "Import error, cannot import name Schema from pydantic" so I downgraded pydantic version to 1.7.4 maybe.
And then I got error messages below.

File "/home/gpuadmin/miniconda3/envs/splatter-image/lib/python3.8/site-packages/fastapi/params.py", line 14, in <module>
    class Param(Schema):
TypeError: cannot create 'cython_function_or_method' instances

I wonder how I can deal with it.

Thank you for reading my issues.

**Comment by 1800012973** [comment]
hello, I meet the same issue. How did you solve it? I followed (https://support.prodi.gy/t/importerror-cannot-import-name-schema-from-pydantic/3948) and installed pydantic==1.7.4 and gradio==3.48
