### ISSUE TITLE
Version of 'gradio'

### ISSUE THREAD

**Issue by 1800012973** [szymanowiczs/splatter-image#44]
Could you tell me the version of ‘gradio’ in requirement.txt? I have trouble when running gradio.py, I tried gradio=4.x but the correspondding 'pydantic' reports:` ImportError: cannot import name 'Schema' from 'pydantic'`. I also tried gradio=3.x but got: `File "gradio_app.py", line 215, in main
    submit.click(fn=check_input_image, inputs=[input_image]).success(
TypeError: click() missing 1 required positional argument: 'outputs'`

**Comment by Riyue120** [comment]
I do not meet this problem.
```
IMPORTANT: You are using gradio version 3.50.2, however version 4.29.0 is available, please upgrade.
```
I think the `__init__.py` file in the `gaussian_renderer` folder needs to be changed in line 84:
```
#rendered_image, radii = rasterizer(
rendered_image, radii, rendered_depth, rendered_alpha = rasterizer(
```
Otherwise, you might run into this problem:
```
 File "/root/splatter-image/gaussian_renderer/__init__.py", line 84, in render_predicted
    rendered_image, radii = rasterizer(
ValueError: too many values to unpack (expected 2)
```

**Comment by 1800012973** [comment]
Thanks, I finally sovled it by installing gradio 3.30 and pydantic 1.7.4
