### ISSUE TITLE
A Question regarding objaverse dataset

### ISSUE THREAD

**Issue by cmh1027** [szymanowiczs/splatter-image#46]
Hello, I'm curious why you used renderings of zero-1-to-3 for objaverse dataset. I believe that you can use the real GT images using blender script provided by objaverse metadata, rather than pseudo-GT from zero-1-to-3. Is there a specific reason for it?

**Comment by szymanowiczs** [comment]
No particular reason, you can experiment with other ways of generating the data but the ones from zero-1-to-3 were already good enough for us.
