### ISSUE TITLE
query regarding the download address of Google Scanned Object (gso) dataset

### ISSUE THREAD

**Issue by Torment123** [szymanowiczs/splatter-image#48]
Hi, I have looked up the dataset address of gso dataset, and found the download address in this website https://app.gazebosim.org/GoogleResearch/fuel/collections/Scanned%20Objects%20by%20Google%20Research, which contains 1032 models, is this entire set what you used to test Splatter Image model? Thanks

**Comment by szymanowiczs** [comment]
Hi! I used renderings from Free3D https://drive.google.com/file/d/1tV-qpiD5e-GzrjW5dQpTRviZa4YV326b/view

there are 1030 models there, so it should be about the same.
