### ISSUE TITLE
The most related paper

### ISSUE THREAD

**Issue by leo-frank** [szymanowiczs/splatter-image#51]
Thanks for your awesome work.

I wonder if there exists any paper that focus on the same task as yours with two attributes: 
+ single image to 3D Gaussians 
+ support feed forward inference

Thanks again for your solid coding!

**Comment by szymanowiczs** [comment]
I think we are the first (and perhaps only?) model to do inference from a single image using Gaussians as an underlying representation. The closest pre-gaussian splatting models are perhaps Point Out Net  https://openaccess.thecvf.com/content_cvpr_2017/papers/Fan_A_Point_Set_CVPR_2017_paper.pdf and SynSin https://arxiv.org/abs/1912.08804
