### ISSUE TITLE
GPU memory usage is unstable

### ISSUE THREAD

**Issue by huangpeng6666** [szymanowiczs/splatter-image#59]
Hello, I faced a problem and didn't know why it happened.
When I trained the splatter-image on my dataset, GPU usage was just 9GB at the beginning, but increasing to 13-14GB later on...
Could you please help explain what part of the training stage may use extra memory later on?

Thanks~

**Comment by szymanowiczs** [comment]
Hi @huangpeng6666 it's possible that the Gaussian Rasterizer allocates more memory, depending on the locations of the Gaussians.

**Comment by szymanowiczs** [comment]
Unfortunately I'm unable to provide more guidance than this. There shouldn't be a memory leak from the network, as I found it to train stably for a long time. 13-14G of memory consumption would be well expected - I trained all models on an A6000 (48G) and would recommend using a GPU that has at least 24G of memory.
