### ISSUE TITLE
Is this model applicable to dynamic objects?

### ISSUE THREAD

**Issue by MichaelWangGo** [szymanowiczs/splatter-image#64]
Hi authors,

A very interesting work!

I want to ask if this model is applicable to dynamic objects?

**Comment by szymanowiczs** [comment]
you can run Splatter Image frame-by-frame on a video - that's how we rendered the dancing teddybear on the website. Be aware though that the model was trained with a fixed focal length and distance from object, as well as the object being in the centre of the image. If these assumptions are not met, the results might be worse. Hope this helps!

**Comment by MichaelWangGo** [comment]
> you can run Splatter Image frame-by-frame on a video - that's how we rendered the dancing teddybear on the website. Be aware though that the model was trained with a fixed focal length and distance from object, as well as the object being in the centre of the image. If these assumptions are not met, the results might be worse. Hope this helps!

Thank you for your reply! Have you tried it on the d-nerf dataset? I see that you trained the model on images with a resolution of 128*128, if I want to train on images with a larger resolution, what else should I consider besides batch size?

**Comment by szymanowiczs** [comment]
I haven't tried on D-nerf! You might want to be careful about the initialization of the sizes and scales of the Gaussians. My intuition is that they should be smaller if you have more of them (due to higher resolution), but I'm not sure how this impacts optimization.

Let me know if you have more questions, otherwise feel free to close the issue :)

**Comment by MichaelWangGo** [comment]
> I haven't tried on D-nerf! You might want to be careful about the initialization of the sizes and scales of the Gaussians. My intuition is that they should be smaller if you have more of them (due to higher resolution), but I'm not sure how this impacts optimization.
> 
> Let me know if you have more questions, otherwise feel free to close the issue :)

Yes sure, thank you so much! Can I ask one more question, what if I input an image including two or more object that I want to reconstruct?

**Comment by szymanowiczs** [comment]
That should be fine, as long as you have some of those in your training set
