### ISSUE TITLE
omegaconf.errors.ConfigAttributeError: Key 'anneal_opacity' is not in struct     full_key: model.anneal_opacity

### ISSUE THREAD

**Issue by zhangzehao123** [szymanowiczs/splatter-image#7]
![屏幕截图 2024-01-03 191120](https://github.com/szymanowiczs/splatter-image/assets/117174448/5345834d-d68f-4425-865a-5eb1d877f61e)zs/splatter-image/assets/117174448/10b4bfd9-0e62-4fbf-862b-f9cbba01f9c8)
Hello, I meet the following errors when running "python train_network.py +dataset=[cars,chairs,hydrants,teddybears]", how can I solve this? I have installed all the packages as requirement.
Thanks a lot for your help!

**Comment by linmi1** [comment]
maybe set HYDRA_FULL_ERROR=1 in environment variable,哈哈

**Comment by szymanowiczs** [comment]
This has been resolved with the latest commit - try pulling the latest version and run again with for example `python train_network.py +dataset=cars`
