### ISSUE TITLE
The version of Pytorch

### ISSUE THREAD

**Issue by sonnefred** [szymanowiczs/splatter-image#8]
<img width="902" alt="图片" src="https://github.com/szymanowiczs/splatter-image/assets/66628395/e807149e-d5a9-450b-b7f7-1410bf709d60">
Hi, could you tell me which versions are supported by this project? I used torch 1.8.1, but got this error. I think it's related to the version of Pytorch. Could you give me any hint about this? Thanks.

**Comment by 13253318778** [comment]
Maybe  pytorch1.12 can solve your problem，I don't have your problem with 1.12, but I do have a problem with dataset preprocessing!

**Comment by szymanowiczs** [comment]
Hi @sonnefred - I verified that the code works with:

- Python 3.7, Pytorch 1.12.1, CUDA 11.6
- Python 3.8, Pytorch 2.1.1, CUDA 12.1

Hopefully this helps. I also updated the instructions in Readme.

**Comment by sonnefred** [comment]
> Hi @sonnefred - I verified that the code works with:
> 
>     * Python 3.7, Pytorch 1.12.1, CUDA 11.6
> 
>     * Python 3.8, Pytorch 2.1.1, CUDA 12.1
> 
> 
> Hopefully this helps. I also updated the instructions in Readme.

Thanks for your reply, and I will have a try!
