### ISSUE TITLE
SRN dataset format

### ISSUE THREAD

**Issue by mengxuyiGit** [szymanowiczs/splatter-image#9]
Hi, I have downloaded **srn_car.zip** and **srn_chair.zip** as instructed in [pixelnerf](https://github.com/sxyu/pixel-nerf?tab=readme-ov-file#shapenet-single-category-srn), but it turns out the data arrangement within the folder is different than that expected to be in the dataloader: there is **no intrisics.txt** in the srn_car folder. Could you provide a correct format for reference or a preprocessed dataset? 

Many thanks!

**Comment by karaokenoway** [comment]
the same question，can you provide a preprocessed dataset?

**Comment by mengxuyiGit** [comment]
Same happens to CO3D dataset: there is no **crop_bbox_xywh** for each sequence, while it is acquired by your dataloader.

**Comment by ngailapdi** [comment]
I downloaded the pre-processed data from this repo and it works fine https://github.com/Lakonik/SSDNeRF/tree/main

**Comment by mengxuyiGit** [comment]
Thanks @ngailapdi , are you able to get the CO3D data as required? This repo seems to only contain SRN data.

**Comment by szymanowiczs** [comment]
Hi @mengxuyiGit - as per instructions on PixelNeRF repo, please download srn_cars.zip and srn_chairs.zip from here: https://drive.google.com/drive/folders/1PsT3uKwqHHD2bEEHkIXB99AlIjtmrEiR . These folders (after unzipping) is what I used. I downloaded the folders just now to double check, and intrinsics.txt are in each object folder, as expected (screenshot attached). I would suggest you download the folders again and make sure you set the data root in the code correctly and let me know if you have further issues. If you're still having issues after this feel free to reopen the issue.

![Screenshot 2024-01-13 at 17 43 38](https://github.com/szymanowiczs/splatter-image/assets/23418488/9c793545-8819-4d0e-8c10-9e43e531d5e7)
